

# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  base = "wordpress-api/"
  publish = "wordpress-api/build/"
  command = "echo 'npm run build'"
  ignore = "git build --quiet HEAD^ HEAD wordpress-api/"









